In [41]:
import pandas as pd
kl=pd.read_csv("Car_sales.csv")
ol=kl.drop(columns=['Manufacturer','Sales_in_thousands','Latest_Launch','__year_resale_value','Power_perf_factor','Curb_weight','Wheelbase','Width','Length'])
io=ol.dropna()#things only needed are selected
io.Engine_size=ol.Engine_size.astype('int')
io.Fuel_capacity=io.Fuel_capacity.astype('int')
io.Price_in_thousands=io.Price_in_thousands.astype("int")#converting float objects to int
io.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 155 entries, 0 to 156
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Model               155 non-null    object
 1   Vehicle_type        155 non-null    object
 2   Price_in_thousands  155 non-null    int32
 3   Engine_size         155 non-null    int32
 4   Horsepower          155 non-null    int64
 5   Fuel_capacity       155 non-null    int32
 6   Fuel_efficiency     155 non-null    int64
dtypes: int32(3), int64(2), object(2)
memory usage: 7.9+ KB

C:\Users\DELL\AppData\Local\Programs\Python\Python39\lib\site-packages\pandas\core\generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [32]:
io

,Model,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity,Fuel_efficiency
0,Integra,Passenger,21,1,140,13,28
1,TL,Passenger,28,3,225,17,25
3,RL,Passenger,42,3,210,18,22
4,A4,Passenger,23,1,150,16,27
5,A6,Passenger,33,2,200,18,22
...,...,...,...,...,...,...,...
152,V40,Passenger,24,1,160,15,25
153,S70,Passenger,27,2,168,17,25
154,V70,Passenger,28,2,168,17,25
155,C70,Passenger,45,2,236,18,23
156,S80,Passenger,36,2,201,21,24

In [55]:
from sklearn import  preprocessing
le=preprocessing.LabelEncoder()#feature is about the given data
label=le.fit_transform(io.Model)
vehicletype_encoded=le.fit_transform(io.Vehicle_type)#label is for what we are gonna predict
features=list(zip(vehicletype_encoded,io.Price_in_thousands,io.Engine_size,io.Horsepower,io.Fuel_capacity,io.Fuel_efficiency ))
from sklearn.neighbors import KNeighborsClassifier#main prediction
model=KNeighborsClassifier(n_neighbors=12)
model.fit(features,label)
print(model.predict_proba([[1,22,0,123,12,45],[1,22,0,123,12,40]]))
print(model.predict([[1,22,0,123,12,45],[1,22,0,123,12,40]]))

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.08333333 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.08333333 0.         0.08333333 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.08333333 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.08333333 0.
  0.         0.         0.         0.         0.         0.08333333
  0.         0.16666667 0.         0.         0.         0.
  0.         0.         0.08333333 0.         0.         0.08333333
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.08333333
  0.         0.         0.         0.08333333 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.08333333 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.08333333 0.         0.
  0.         0.         0.08333333 0.         0.08333333 0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.08333333 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.08333333 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.08333333 0.
  0.         0.         0.         0.         0.         0.08333333
  0.         0.         0.         0.         0.         0.
  0.         0.         0.08333333 0.         0.         0.08333333
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.08333333
  0.         0.         0.         0.08333333 0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]]
[103  28]

In [43]:
features

[(1, 21, 1, 140, 13, 28),
 (1, 28, 3, 225, 17, 25),
 (1, 42, 3, 210, 18, 22),
 (1, 23, 1, 150, 16, 27),
 (1, 33, 2, 200, 18, 22),
 (1, 62, 4, 310, 23, 21),
 (1, 26, 2, 170, 16, 26),
 (1, 33, 2, 193, 16, 24),
 (1, 38, 2, 193, 18, 25),
 (1, 21, 3, 175, 17, 25),
 (1, 25, 3, 240, 17, 23),
 (1, 31, 3, 205, 18, 24),
 (1, 27, 3, 205, 17, 25),
 (1, 39, 4, 275, 18, 22),
 (1, 44, 4, 275, 18, 22),
 (1, 39, 4, 275, 19, 22),
 (1, 31, 3, 200, 18, 22),
 (0, 46, 5, 255, 30, 15),
 (1, 13, 2, 115, 14, 27),
 (1, 16, 3, 170, 15, 25),
 (1, 18, 3, 175, 16, 25),
 (1, 19, 3, 180, 17, 27),
 (1, 24, 3, 200, 16, 25),
 (1, 45, 5, 345, 19, 22),
 (1, 13, 1, 120, 13, 33),
 (1, 9, 1, 55, 10, 45),
 (1, 18, 3, 180, 17, 27),
 (1, 19, 2, 163, 15, 24),
 (1, 24, 2, 168, 16, 24),
 (1, 22, 2, 200, 17, 26),
 (1, 16, 2, 132, 16, 27),
 (1, 28, 3, 253, 17, 23),
 (1, 29, 3, 253, 17, 23),
 (1, 12, 2, 132, 12, 29),
 (1, 19, 2, 163, 15, 24),
 (1, 20, 2, 168, 16, 24),
 (1, 22, 2, 202, 17, 25),
 (1, 69, 8, 450, 19, 16),
 (0, 19, 5, 230, 26, 17),
 (0, 21, 3, 175, 32, 15),
 (0, 18, 3, 175, 32, 16),
 (0, 16, 2, 120, 22, 19),
 (0, 26, 5, 230, 25, 17),
 (0, 19, 2, 150, 20, 24),
 (1, 12, 2, 110, 12, 30),
 (1, 21, 3, 190, 15, 24),
 (1, 17, 2, 170, 15, 25),
 (1, 17, 3, 155, 16, 24),
 (1, 12, 2, 107, 13, 30),
 (1, 22, 4, 200, 19, 21),
 (0, 31, 4, 210, 21, 19),
 (0, 21, 3, 150, 26, 21),
 (0, 36, 4, 240, 26, 16),
 (0, 12, 2, 119, 20, 23),
 (0, 26, 4, 220, 25, 18),
 (1, 12, 1, 106, 11, 32),
 (1, 15, 2, 135, 17, 27),
 (0, 20, 2, 146, 15, 24),
 (0, 26, 3, 205, 21, 19),
 (0, 26, 3, 210, 20, 23),
 (1, 9, 1, 92, 11, 31),
 (1, 11, 2, 140, 14, 27),
 (1, 14, 2, 148, 17, 25),
 (1, 29, 3, 227, 18, 25),
 (1, 42, 3, 240, 18, 21),
 (0, 14, 2, 120, 19, 17),
 (0, 21, 4, 190, 20, 20),
 (0, 26, 4, 195, 20, 19),
 (1, 31, 3, 210, 18, 23),
 (1, 37, 3, 225, 19, 23),
 (1, 46, 4, 300, 19, 21),
 (1, 54, 4, 290, 22, 22),
 (0, 60, 4, 230, 25, 15),
 (0, 34, 3, 220, 17, 21),
 (1, 39, 4, 275, 20, 22),
 (1, 43, 4, 215, 19, 21),
 (0, 42, 5, 300, 30, 15),
 (1, 13, 1, 113, 13, 30),
 (1, 19, 2, 154, 15, 24),
 (1, 17, 2, 145, 16, 25),
 (1, 24, 3, 210, 19, 22),
 (1, 25, 3, 161, 19, 21),
 (0, 31, 3, 200, 24, 18),
 (0, 22, 3, 173, 19, 20),
 (1, 16, 2, 125, 15, 28),
 (1, 16, 2, 125, 16, 30),
 (1, 19, 3, 153, 16, 24),
 (1, 22, 4, 200, 19, 21),
 (0, 27, 4, 210, 21, 18),
 (0, 22, 3, 170, 20, 21),
 (1, 31, 2, 185, 16, 26),
 (1, 49, 3, 221, 21, 25),
 (1, 69, 4, 275, 23, 21),
 (1, 82, 5, 302, 21, 20),
 (1, 38, 2, 190, 15, 26),
 (1, 41, 2, 185, 14, 27),
 (1, 41, 3, 215, 16, 26),
 (1, 85, 5, 302, 23, 20),
 (0, 35, 3, 215, 19, 20),
 (1, 13, 1, 126, 13, 30),
 (1, 20, 2, 155, 15, 25),
 (1, 26, 3, 222, 18, 25),
 (0, 26, 3, 170, 20, 21),
 (0, 29, 3, 170, 21, 19),
 (0, 22, 3, 170, 19, 18),
 (0, 17, 3, 170, 19, 18),
 (1, 18, 3, 150, 15, 25),
 (1, 24, 3, 215, 18, 27),
 (1, 18, 2, 150, 15, 27),
 (1, 36, 4, 250, 18, 22),
 (0, 31, 4, 190, 17, 19),
 (0, 25, 3, 185, 25, 22),
 (1, 12, 2, 132, 12, 29),
 (1, 16, 2, 132, 16, 27),
 (0, 18, 2, 150, 20, 24),
 (1, 43, 3, 253, 12, 21),
 (1, 21, 2, 150, 15, 27),
 (1, 19, 3, 175, 15, 25),
 (1, 25, 3, 200, 16, 25),
 (1, 21, 3, 195, 18, 25),
 (1, 23, 3, 205, 17, 24),
 (0, 25, 3, 185, 25, 23),
 (1, 41, 2, 217, 17, 22),
 (1, 71, 3, 300, 17, 21),
 (1, 74, 3, 300, 17, 23),
 (1, 33, 2, 170, 18, 23),
 (1, 26, 2, 185, 16, 23),
 (1, 10, 1, 100, 12, 33),
 (1, 12, 1, 100, 12, 33),
 (1, 14, 1, 124, 12, 31),
 (1, 18, 2, 137, 13, 27),
 (1, 15, 2, 137, 13, 28),
 (1, 22, 2, 165, 16, 25),
 (0, 20, 2, 165, 15, 24),
 (1, 13, 1, 120, 13, 33),
 (1, 17, 2, 133, 18, 27),
 (1, 25, 3, 210, 18, 26),
 (1, 16, 1, 140, 14, 31),
 (0, 11, 2, 142, 15, 23),
 (0, 22, 3, 194, 20, 22),
 (0, 16, 2, 127, 15, 27),
 (0, 22, 2, 150, 18, 23),
 (0, 51, 4, 230, 25, 15),
 (1, 14, 2, 115, 14, 26),
 (1, 16, 2, 115, 14, 26),
 (1, 21, 1, 150, 16, 27),
 (1, 19, 2, 115, 13, 26),
 (1, 17, 2, 115, 14, 26),
 (1, 15, 2, 115, 14, 26),
 (1, 23, 1, 160, 15, 25),
 (1, 24, 1, 160, 15, 25),
 (1, 27, 2, 168, 17, 25),
 (1, 28, 2, 168, 17, 25),
 (1, 45, 2, 236, 18, 23),
 (1, 36, 2, 201, 21, 24)]

In [46]:
label

array([ 78, 142, 114,   8,   9,  10,   3,   4,   7,  37, 120, 106,  88,
        50, 136,  57,  34,  58,  35,  91,  89,  96,  29,  45, 110,  93,
        77, 134, 133,  41,  39,  82,   2, 103,  17, 140,  79, 149, 116,
       118, 117,  49,  52,  31,  59, 100,  43, 144,  64,  47,  61, 151,
        60, 119,  62,  40,  12,  27, 108, 104,  11,  56, 139,  76, 122,
       152,  38,  73,  54,  67,  68,  84,  86, 115,  42, 145, 102,  94,
        55,  70,  51,   1,  97,  98, 101,  46, 132,  74,  99, 148,  23,
        53, 121, 128, 129, 130,  26,  25,  90, 135,  14,  92, 112, 109,
       153,  66,  48,  80,  13,  15,  21, 138, 103,  22, 150, 111, 141,
        72,  63,  75,  19,  95,  20,  33,  32,   6,   0, 127, 126, 131,
        85,  83, 105,  65,  44,  30,  16,  36, 143, 137, 113,   5,  87,
        71,  81, 107,  28,  69,  18, 123, 146, 124, 147,  24, 125])