In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
kl=pd.read_csv('F:\dat anlysis\paragraph.csv')
klo=kl.iloc[::,0:3]
klo

    year  board            title
0   2015      2               Wm
1   2017      1               Wm
2   2017      8               Wm
3   2015      1                G
4   2015      0                P
5   2019      0                p
6   2017      0                p
7   2016      8                t
8   2015      5                t
9   2016      0               rb
10  2015      4               rb
11  2019      7               rb
12  2017      7               rb
13  2019      2               tr
14  2016      2               tr
15  2019      3               tr
16  2015      3               tr
17  2019      1                W
18  2015      1                W
19  2015      7               rd
20  2017      1                l
21  2015      8                l
22  2017      8               vd
23  2016      8               vd
24  2015      5               vd
25  2019      0               pb
26  2017      0               pb
27  2015      0               pb
28  2015      2               pb
29  2017      4               pb
30  2015      4               pb
31  2017      7               pb
32  2015      7               pb
33  2015      3             last
34  2015      8         internet
35  2016      5         internet
36  2019      8      childkabour
37  2019      2      childkabour
38  2017      2      childkabour
39  2017      2             food
40  2016      4             food
41  2019      4             food
42  2016      2      villagefair
43  2017      4        liberaday
44  2016      5        liberaday
45  2018      6            dowry
46  2016      3          digital
47  2016      7            dowry
48  2016      3        guestbird
49  2019      1          library
50  2019      7            sring
51  2019      8  beautifulbangla
52  2019      3         childmem

In [10]:
x=klo.drop(columns='title')
y=klo.title
x_train ,x_test, y_train ,y_test = train_test_split(x ,y ,test_size=0.8)
model =DecisionTreeClassifier()
l=model.fit(x_train,y_train)
lo=model.predict(x_test,l)
asl=accuracy_score(lo,y_test)
asl

0.023255813953488372